spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
spring.datasource.modulocilindro.url=${MODULO_CIL_URL}
spring.datasource.modulocilindro.username=${MODULO_CIL_USER}
spring.datasource.modulocilindro.password=${MODULO_CIL_PASS}
spring.datasource.modulocilindro.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.seguridad.url=${SEGURIDAD_URL}
spring.datasource.seguridad.username=${SEGURIDAD_USER}
spring.datasource.seguridad.password=${SEGURIDAD_PASS}
spring.datasource.seguridad.driver-class-name=oracle.jdbc.OracleDriver

server.port=${SERVER_PORT:8087}


spring.mail.host=smtp.dreamhost.com
spring.mail.port=587
spring.mail.username=${EMAIL_EMISOR}
spring.mail.password=${EMAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=300000