spring.application.name=backend
// Local
spring.datasource.modulocilindro.url=jdbc:oracle:thin:@//107.23.42.217:1521/XE
// Server
// spring.datasource.modulocilindro.url=jdbc:oracle:thin:@172.31.29.167:1521:XE
spring.datasource.modulocilindro.username=gtmadmcon55
spring.datasource.modulocilindro.password=nvacta55
spring.datasource.modulocilindro.driver-class-name=oracle.jdbc.OracleDriver

// Local
spring.datasource.seguridad.url=jdbc:oracle:thin:@//107.23.42.217:1521/XE
// Server
//spring.datasource.seguridad.url=jdbc:oracle:thin:@172.31.29.167:1521:XE
spring.datasource.seguridad.username=GTMSEGURIDAD
spring.datasource.seguridad.password=israel70
spring.datasource.seguridad.driver-class-name=oracle.jdbc.OracleDriver
server.port = 8087